-- 출처:https://school.programmers.co.kr/learn/courses/30/lessons/131537



SELECT LEFT(SALES_DATE,10) AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE 
WHERE MID(SALES_DATE,1,7) = '2022-03'
UNION ALL
SELECT LEFT(SALES_DATE,10) AS SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE
WHERE MID(SALES_DATE,1,7) = '2022-03'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC